/*  https://chatgpt.com/share/69533b20-249c-8013-8dfa-62f7258763d3
Generate 100+ countries as a JavaScript array with code and name properties
Format each entry as: { code: "XX", name: "Country Name" }
Translate the country name to norwegian
Include comments to separate each region
*/

//lite praktsik......... må fikses på. jeg må ha de landene some r i kravet først 
export const COUNTRIES = [
  { code: "DZ", name: "Algerie" },
  { code: "AO", name: "Angola" },
  { code: "BJ", name: "Benin" },
  { code: "BW", name: "Botswana" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Kapp Verde" },
  { code: "CM", name: "Kamerun" },
  { code: "CF", name: "Den sentralafrikanske republikk" },
  { code: "TD", name: "Tsjad" },
  { code: "KM", name: "Komorene" },
  { code: "CD", name: "Den demokratiske republikken Kongo" },
  { code: "CG", name: "Republikken Kongo" },
  { code: "CI", name: "Elfenbenskysten" },
  { code: "DJ", name: "Djibouti" },
  { code: "EG", name: "Egypt" },
  { code: "GQ", name: "Ekvatorial-Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Etiopia" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GH", name: "Ghana" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "KE", name: "Kenya" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "MG", name: "Madagaskar" },
  { code: "MW", name: "Malawi" },
  { code: "ML", name: "Mali" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MA", name: "Marokko" },
  { code: "MZ", name: "Mosambik" },
  { code: "NA", name: "Namibia" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "RW", name: "Rwanda" },
  { code: "ST", name: "São Tomé og Príncipe" },
  { code: "SN", name: "Senegal" },
  { code: "SC", name: "Seychellene" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "Sør-Afrika" },
  { code: "SS", name: "Sør-Sudan" },
  { code: "SD", name: "Sudan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TG", name: "Togo" },
  { code: "TN", name: "Tunisia" },
  { code: "UG", name: "Uganda" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },

  // Europa
  { code: "AL", name: "Albania" },
  { code: "AD", name: "Andorra" },
  { code: "AM", name: "Armenia" },
  { code: "AT", name: "Østerrike" },
  { code: "AZ", name: "Aserbajdsjan" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgia" },
  { code: "BA", name: "Bosnia-Hercegovina" },
  { code: "BG", name: "Bulgaria" },
  { code: "HR", name: "Kroatia" },
  { code: "CY", name: "Kypros" },
  { code: "CZ", name: "Tsjekkia" },
  { code: "DK", name: "Danmark" },
  { code: "EE", name: "Estland" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "Frankrike" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Tyskland" },
  { code: "GR", name: "Hellas" },
  { code: "HU", name: "Ungarn" },
  { code: "IS", name: "Island" },
  { code: "IE", name: "Irland" },
  { code: "IT", name: "Italia" },
  { code: "XK", name: "Kosovo" },
  { code: "LV", name: "Latvia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Litauen" },
  { code: "LU", name: "Luxembourg" },
  { code: "MT", name: "Malta" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "ME", name: "Montenegro" },
  { code: "NL", name: "Nederland" },
  { code: "MK", name: "Nord-Makedonia" },
  { code: "NO", name: "Norge" },
  { code: "PL", name: "Polen" },
  { code: "PT", name: "Portugal" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russland" },
  { code: "SM", name: "San Marino" },
  { code: "RS", name: "Serbia" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "ES", name: "Spania" },
  { code: "SE", name: "Sverige" },
  { code: "CH", name: "Sveits" },
  { code: "TR", name: "Tyrkia" },
  { code: "UA", name: "Ukraina" },
  { code: "GB", name: "Storbritannia" },
  { code: "VA", name: "Vatikanstaten" },

  // Asia
  { code: "AF", name: "Afghanistan" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BT", name: "Bhutan" },
  { code: "BN", name: "Brunei" },
  { code: "KH", name: "Kambodsja" },
  { code: "CN", name: "Kina" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Irak" },
  { code: "IL", name: "Israel" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kasakhstan" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kirgisistan" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Libanon" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldivene" },
  { code: "MN", name: "Mongolia" },
  { code: "MM", name: "Myanmar" },
  { code: "NP", name: "Nepal" },
  { code: "KP", name: "Nord-Korea" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PH", name: "Filippinene" },
  { code: "QA", name: "Qatar" },
  { code: "SA", name: "Saudi-Arabia" },
  { code: "SG", name: "Singapore" },
  { code: "KR", name: "Sør-Korea" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tadsjikistan" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TM", name: "Turkmenistan" },
  { code: "AE", name: "De forente arabiske emirater" },
  { code: "UZ", name: "Usbekistan" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Jemen" },

  // Nord-Amerika
  { code: "CA", name: "Canada" },
  { code: "US", name: "USA" },
  { code: "MX", name: "Mexico" },
  { code: "GT", name: "Guatemala" },
  { code: "BZ", name: "Belize" },
  { code: "HN", name: "Honduras" },
  { code: "SV", name: "El Salvador" },
  { code: "NI", name: "Nicaragua" },
  { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panama" },
  { code: "CU", name: "Cuba" },
  { code: "DO", name: "Den dominikanske republikk" },
  { code: "HT", name: "Haiti" },
  { code: "JM", name: "Jamaica" },
  { code: "TT", name: "Trinidad og Tobago" },
  { code: "BS", name: "Bahamas" },
  { code: "BB", name: "Barbados" },

  // Sør-Amerika
  { code: "AR", name: "Argentina" },
  { code: "BO", name: "Bolivia" },
  { code: "BR", name: "Brasil" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "EC", name: "Ecuador" },
  { code: "GY", name: "Guyana" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "SR", name: "Surinam" },
  { code: "UY", name: "Uruguay" },
  { code: "VE", name: "Venezuela" },

  // Oseania
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "FJ", name: "Fiji" },
  { code: "PG", name: "Papua Ny-Guinea" },
  { code: "SB", name: "Salomonøyene" },
  { code: "VU", name: "Vanuatu" },
  { code: "WS", name: "Samoa" },
  { code: "TO", name: "Tonga" },
  { code: "FM", name: "Mikronesiaføderasjonen" },
  { code: "KI", name: "Kiribati" },
  { code: "NR", name: "Nauru" },
  { code: "TV", name: "Tuvalu" },
];

